<?php

return [
    'company' => [
        'name' => 'TechOrbit IT',
        'mark' => 'TechOrbit',
        'tagline' => [
            'en' => 'Software company from Bangladesh delivering modern digital products.',
            'bn' => 'বাংলাদেশের একটি সফটওয়্যার প্রতিষ্ঠান, যারা আধুনিক ডিজিটাল পণ্য তৈরি করে।',
        ],
        'footer_about' => [
            'en' => 'We help startups, SMEs, and enterprise teams move faster with web platforms, mobile apps, ERP systems, and thoughtful product design.',
            'bn' => 'আমরা স্টার্টআপ, এসএমই এবং এন্টারপ্রাইজ টিমকে ওয়েব প্ল্যাটফর্ম, মোবাইল অ্যাপ, ERP সিস্টেম এবং কার্যকর প্রোডাক্ট ডিজাইনের মাধ্যমে দ্রুত এগিয়ে যেতে সহায়তা করি।',
        ],
        'location' => [
            'en' => 'Dhaka, Bangladesh',
            'bn' => 'ঢাকা, বাংলাদেশ',
        ],
        'email' => 'info@techorbitit.com',
        'phone' => '+880 1712-345678',
        'whatsapp' => '+8801712345678',
        'address' => [
            'en' => 'House 18, Road 07, Sector 04, Uttara, Dhaka 1230',
            'bn' => 'হাউস ১৮, রোড ০৭, সেক্টর ০৪, উত্তরা, ঢাকা ১২৩০',
        ],
        'socials' => [
            ['label' => 'Facebook', 'url' => 'https://facebook.com'],
            ['label' => 'LinkedIn', 'url' => 'https://linkedin.com'],
            ['label' => 'GitHub', 'url' => 'https://github.com'],
        ],
    ],
    'navigation' => [
        ['label' => ['en' => 'Home', 'bn' => 'হোম'], 'route' => 'site.home'],
        ['label' => ['en' => 'Services', 'bn' => 'সেবাসমূহ'], 'route' => 'site.services'],
        ['label' => ['en' => 'Portfolio', 'bn' => 'পোর্টফোলিও'], 'route' => 'site.portfolio'],
        ['label' => ['en' => 'About', 'bn' => 'আমাদের সম্পর্কে'], 'route' => 'site.about'],
        ['label' => ['en' => 'Blog', 'bn' => 'ব্লগ'], 'route' => 'site.blog'],
        ['label' => ['en' => 'Contact', 'bn' => 'যোগাযোগ'], 'route' => 'site.contact'],
        ['label' => ['en' => 'Our Software', 'bn' => 'আমাদের সফটওয়্যার'], 'route' => 'site.software'],
    ],
    'meta' => [
        'home' => [
            'title' => ['en' => 'TechOrbit IT | Modern Software Company in Bangladesh', 'bn' => 'TechOrbit IT | বাংলাদেশের আধুনিক সফটওয়্যার কোম্পানি'],
            'description' => ['en' => 'Custom software, mobile apps, ERP, CRM, and design systems for growing businesses.', 'bn' => 'বর্ধনশীল ব্যবসার জন্য কাস্টম সফটওয়্যার, মোবাইল অ্যাপ, ERP, CRM এবং ডিজাইন সিস্টেম।'],
        ],
        'services' => [
            'title' => ['en' => 'Services | TechOrbit IT', 'bn' => 'সেবাসমূহ | TechOrbit IT'],
            'description' => ['en' => 'Explore TechOrbit IT services across web, mobile, ERP, cloud, design, and consulting.', 'bn' => 'ওয়েব, মোবাইল, ERP, ক্লাউড, ডিজাইন এবং কনসাল্টিংয়ে TechOrbit IT এর সেবা দেখুন।'],
        ],
        'portfolio' => [
            'title' => ['en' => 'Portfolio | TechOrbit IT', 'bn' => 'পোর্টফোলিও | TechOrbit IT'],
            'description' => ['en' => 'A selection of product launches, business systems, and mobile experiences built by TechOrbit IT.', 'bn' => 'TechOrbit IT নির্মিত প্রোডাক্ট, বিজনেস সিস্টেম এবং মোবাইল অভিজ্ঞতার একটি নির্বাচিত সংগ্রহ।'],
        ],
        'about' => [
            'title' => ['en' => 'About Us | TechOrbit IT', 'bn' => 'আমাদের সম্পর্কে | TechOrbit IT'],
            'description' => ['en' => 'Meet the team, values, and delivery approach behind TechOrbit IT.', 'bn' => 'TechOrbit IT এর টিম, মূল্যবোধ এবং ডেলিভারি পদ্ধতি সম্পর্কে জানুন।'],
        ],
        'blog' => [
            'title' => ['en' => 'Blog | TechOrbit IT', 'bn' => 'ব্লগ | TechOrbit IT'],
            'description' => ['en' => 'Insights on product strategy, Laravel, mobile apps, and digital transformation.', 'bn' => 'প্রোডাক্ট স্ট্র্যাটেজি, Laravel, মোবাইল অ্যাপ এবং ডিজিটাল রূপান্তর নিয়ে ইনসাইট।'],
        ],
        'contact' => [
            'title' => ['en' => 'Contact | TechOrbit IT', 'bn' => 'যোগাযোগ | TechOrbit IT'],
            'description' => ['en' => 'Get in touch with TechOrbit IT to discuss your next software project.', 'bn' => 'আপনার পরবর্তী সফটওয়্যার প্রজেক্ট নিয়ে আলোচনা করতে TechOrbit IT এর সাথে যোগাযোগ করুন।'],
        ],
    ],
    'ui' => [
        'quote_cta' => ['en' => 'Get a Quote', 'bn' => 'কোট নিন'],
        'free_consultation' => ['en' => 'Get a Free Consultation', 'bn' => 'বিনামূল্যে পরামর্শ নিন'],
        'view_work' => ['en' => 'View Our Work', 'bn' => 'আমাদের কাজ দেখুন'],
        'learn_more' => ['en' => 'Learn More', 'bn' => 'আরও জানুন'],
        'view_all_services' => ['en' => 'View All Services', 'bn' => 'সব সেবা দেখুন'],
        'view_all_projects' => ['en' => 'View All Projects', 'bn' => 'সব প্রজেক্ট দেখুন'],
        'view_all_articles' => ['en' => 'View All Articles', 'bn' => 'সব আর্টিকেল দেখুন'],
        'whatsapp_us' => ['en' => 'WhatsApp Us', 'bn' => 'হোয়াটসঅ্যাপ করুন'],
        'ready_title' => ['en' => 'Ready to Start Your Project?', 'bn' => 'আপনার প্রজেক্ট শুরু করতে প্রস্তুত?'],
        'ready_copy' => ['en' => 'Tell us what you are building and we will shape the right team, scope, and timeline around it.', 'bn' => 'আপনি কী তৈরি করতে চান তা জানান, আমরা সেই অনুযায়ী সঠিক টিম, স্কোপ এবং টাইমলাইন সাজিয়ে দেব।'],
        'book_call' => ['en' => 'Book a Discovery Call', 'bn' => 'ডিসকভারি কল বুক করুন'],
        'our_software' => ['en' => 'Our Software', 'bn' => 'আমাদের সফটওয়্যার'],
        'our_software_title' => ['en' => 'Software Products Built for Real Business Operations', 'bn' => 'বাস্তব ব্যবসায়িক কাজের জন্য তৈরি সফটওয়্যার প্রোডাক্ট'],
        'our_software_copy' => ['en' => 'Showcase your software with product copy, demo links, and visuals that help visitors understand what each solution does.', 'bn' => 'প্রতিটি সফটওয়্যার কী কাজ করে তা বোঝাতে প্রোডাক্ট কপি, ডেমো লিংক এবং ভিজ্যুয়ালসহ আপনার সফটওয়্যার তুলে ধরুন।'],
        'call_now' => ['en' => 'Call Now', 'bn' => 'এখনই কল করুন'],
        'watch_demo' => ['en' => 'Watch Demo', 'bn' => 'ডেমো দেখুন'],
    ],
    'heroSlides' => [
        [
            'badge' => ['en' => 'Software Company - Bangladesh', 'bn' => 'বাংলাদেশের সফটওয়্যার কোম্পানি'],
            'title' => ['en' => 'We Build Software That Drives Business Forward', 'bn' => 'আমরা এমন সফটওয়্যার তৈরি করি যা ব্যবসাকে এগিয়ে নিয়ে যায়'],
            'subtitle' => ['en' => 'Custom web apps, mobile products, ERP systems, and product design tailored for ambitious teams.', 'bn' => 'উদ্যোগী টিমগুলোর জন্য কাস্টম ওয়েব অ্যাপ, মোবাইল প্রোডাক্ট, ERP সিস্টেম এবং প্রোডাক্ট ডিজাইন।'],
            'eyebrow' => ['en' => 'Launch faster with a partner that understands delivery, clarity, and scale.', 'bn' => 'ডেলিভারি, স্বচ্ছতা এবং স্কেল বোঝে এমন পার্টনারের সাথে দ্রুত এগিয়ে যান।'],
        ],
        [
            'badge' => ['en' => 'Product Engineering Partner', 'bn' => 'প্রোডাক্ট ইঞ্জিনিয়ারিং পার্টনার'],
            'title' => ['en' => 'From Idea to Launch, We Move With Your Team', 'bn' => 'আইডিয়া থেকে লঞ্চ পর্যন্ত আমরা আপনার টিমের সাথে কাজ করি'],
            'subtitle' => ['en' => 'Discovery workshops, UX systems, agile delivery, and scalable backend architecture in one focused workflow.', 'bn' => 'ডিসকভারি ওয়ার্কশপ, UX সিস্টেম, অ্যাজাইল ডেলিভারি এবং স্কেলযোগ্য ব্যাকএন্ড আর্কিটেকচার একসাথে।'],
            'eyebrow' => ['en' => 'Flexible collaboration for startups, agencies, and enterprise transformation teams.', 'bn' => 'স্টার্টআপ, এজেন্সি এবং এন্টারপ্রাইজ ট্রান্সফরমেশন টিমের জন্য নমনীয় সহযোগিতা।'],
        ],
        [
            'badge' => ['en' => 'ERP, CRM & Automation', 'bn' => 'ERP, CRM ও অটোমেশন'],
            'title' => ['en' => 'Replace Spreadsheet Chaos With Connected Systems', 'bn' => 'স্প্রেডশিটের বিশৃঙ্খলা বদলে নিন সংযুক্ত সিস্টেমে'],
            'subtitle' => ['en' => 'We streamline operations with dashboards, workflows, reports, and integrations that teams actually enjoy using.', 'bn' => 'ড্যাশবোর্ড, ওয়ার্কফ্লো, রিপোর্ট এবং ব্যবহারবান্ধব ইন্টিগ্রেশনের মাধ্যমে আমরা অপারেশন সহজ করি।'],
            'eyebrow' => ['en' => 'Built for speed, visibility, and measurable ROI.', 'bn' => 'গতি, দৃশ্যমানতা এবং বাস্তব ROI এর জন্য তৈরি।'],
        ],
    ],
    'software' => [
        [
            'badge' => ['en' => 'Retail & POS', 'bn' => 'রিটেইল এবং POS'],
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'Best POS Software for Billing, Inventory, Accounting, and Daily Sales', 'bn' => 'বিলিং, ইনভেন্টরি, একাউন্টিং এবং দৈনিক বিক্রির জন্য সেরা POS সফটওয়্যার'],
            'excerpt' => ['en' => 'A complete retail solution for shops, showrooms, and wholesale businesses.', 'bn' => 'দোকান, শোরুম এবং হোলসেল ব্যবসার জন্য একটি পূর্ণাঙ্গ রিটেইল সলিউশন।'],
            'description' => ['en' => 'Present your POS software with pricing-friendly messaging, clear business benefits, and a direct video demo. This layout is ideal for highlighting billing flow, stock management, reporting, customer tracking, and owner dashboards in one focused section.', 'bn' => 'দাম-সহায়ক মেসেজিং, পরিষ্কার ব্যবসায়িক সুবিধা এবং সরাসরি ভিডিও ডেমোসহ আপনার POS সফটওয়্যার তুলে ধরুন। বিলিং ফ্লো, স্টক ম্যানেজমেন্ট, রিপোর্টিং, কাস্টমার ট্র্যাকিং এবং মালিকের ড্যাশবোর্ড এক জায়গায় দেখানোর জন্য এই লেআউটটি আদর্শ।'],
            'video_url' => 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
        ],
        [
            'badge' => ['en' => 'School Management', 'bn' => 'স্কুল ম্যানেজমেন্ট'],
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'Smart School Management Software for Admissions, Fees, Exams, and Attendance', 'bn' => 'অ্যাডমিশন, ফি, পরীক্ষা এবং উপস্থিতির জন্য স্মার্ট স্কুল ম্যানেজমেন্ট সফটওয়্যার'],
            'excerpt' => ['en' => 'One system for institute admins, teachers, accountants, students, and guardians.', 'bn' => 'ইনস্টিটিউট অ্যাডমিন, শিক্ষক, একাউন্টস, শিক্ষার্থী এবং অভিভাবকদের জন্য এক সিস্টেম।'],
            'description' => ['en' => 'Use this section to explain how your education software reduces paperwork and keeps operations connected. Add your real product image and a demo video link from YouTube or Facebook to help visitors understand the workflow before they contact you.', 'bn' => 'এই সেকশনে দেখাতে পারবেন কীভাবে আপনার এডুকেশন সফটওয়্যার কাগজের কাজ কমায় এবং সব অপারেশনকে সংযুক্ত রাখে। ভিজিটররা যোগাযোগ করার আগেই যেন ওয়ার্কফ্লো বুঝতে পারে, সে জন্য এখানে আপনার আসল প্রোডাক্ট ছবি এবং YouTube বা Facebook ডেমো ভিডিও লিংক যোগ করুন।'],
            'video_url' => 'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
        ],
    ],
    'stats' => [
        ['value' => '50+', 'label' => ['en' => 'Projects Delivered', 'bn' => 'সম্পন্ন প্রজেক্ট']],
        ['value' => '30+', 'label' => ['en' => 'Happy Clients', 'bn' => 'সন্তুষ্ট ক্লায়েন্ট']],
        ['value' => '5+', 'label' => ['en' => 'Years Experience', 'bn' => 'বছরের অভিজ্ঞতা']],
        ['value' => '12+', 'label' => ['en' => 'Team Members', 'bn' => 'টিম সদস্য']],
    ],
    'servicesIntro' => [
        'eyebrow' => ['en' => 'What We Do', 'bn' => 'আমরা যা করি'],
        'title' => ['en' => 'End-to-End Digital Delivery', 'bn' => 'শুরু থেকে শেষ পর্যন্ত ডিজিটাল ডেলিভারি'],
        'copy' => ['en' => 'Strategy, design, development, and support for products that need to ship well and grow safely.', 'bn' => 'যে প্রোডাক্টকে সুন্দরভাবে লঞ্চ ও নিরাপদে স্কেল করতে হয়, তার জন্য স্ট্র্যাটেজি, ডিজাইন, ডেভেলপমেন্ট এবং সাপোর্ট।'],
    ],
    'subscriptionOffers' => [
        'eyebrow' => ['en' => 'SaaS & E-commerce Plans', 'bn' => 'SaaS ও ই-কমার্স প্ল্যান'],
        'title' => ['en' => 'Website Subscription Packages for Growing Businesses', 'bn' => 'বর্ধনশীল ব্যবসার জন্য ওয়েবসাইট সাবস্ক্রিপশন প্যাকেজ'],
        'copy' => ['en' => 'Launch faster with monthly website packages for SaaS products, company sites, and e-commerce businesses without a large one-time build cost.', 'bn' => 'এককালীন বড় খরচ ছাড়াই SaaS প্রোডাক্ট, কোম্পানি ওয়েবসাইট এবং ই-কমার্স ব্যবসার জন্য মাসিক ওয়েবসাইট প্যাকেজে দ্রুত শুরু করুন।'],
        'note' => ['en' => 'Perfect for businesses that want design, development, maintenance, and steady improvement under one monthly plan.', 'bn' => 'যেসব ব্যবসা ডিজাইন, ডেভেলপমেন্ট, মেইনটেন্যান্স এবং ধারাবাহিক উন্নয়ন এক মাসিক প্ল্যানে চায়, তাদের জন্য আদর্শ।'],
        'plans' => [
            [
                'badge' => ['en' => 'Starter', 'bn' => 'স্টার্টার'],
                'name' => ['en' => 'Launch 499', 'bn' => 'লঞ্চ ৪৯৯'],
                'price' => '499',
                'currency' => ['en' => 'TK', 'bn' => 'টাকা'],
                'period' => ['en' => '/month', 'bn' => '/মাস'],
                'summary' => ['en' => 'A simple subscription website for freelancers, small shops, and new businesses that need an online presence fast.', 'bn' => 'ফ্রিল্যান্সার, ছোট দোকান এবং নতুন ব্যবসার জন্য দ্রুত অনলাইন উপস্থিতি তৈরির সহজ সাবস্ক্রিপশন ওয়েবসাইট।'],
                'features' => [
                    ['en' => 'Landing page or basic company website', 'bn' => 'ল্যান্ডিং পেজ বা বেসিক কোম্পানি ওয়েবসাইট'],
                    ['en' => 'Mobile-friendly responsive layout', 'bn' => 'মোবাইল-ফ্রেন্ডলি রেসপন্সিভ লে-আউট'],
                    ['en' => 'Basic support and monthly updates', 'bn' => 'বেসিক সাপোর্ট ও মাসিক আপডেট'],
                ],
            ],
            [
                'badge' => ['en' => 'Most Popular', 'bn' => 'সবচেয়ে জনপ্রিয়'],
                'name' => ['en' => 'Business 999', 'bn' => 'বিজনেস ৯৯৯'],
                'price' => '999',
                'currency' => ['en' => 'TK', 'bn' => 'টাকা'],
                'period' => ['en' => '/month', 'bn' => '/মাস'],
                'summary' => ['en' => 'Best for service companies, SaaS startups, and teams that need a stronger website with lead capture and better presentation.', 'bn' => 'সার্ভিস কোম্পানি, SaaS স্টার্টআপ এবং যেসব টিম লিড ক্যাপচারসহ আরও শক্তিশালী ওয়েবসাইট চায় তাদের জন্য উপযুক্ত।'],
                'features' => [
                    ['en' => 'Multi-page business or SaaS website', 'bn' => 'মাল্টি-পেজ বিজনেস বা SaaS ওয়েবসাইট'],
                    ['en' => 'Contact forms, service sections, and CTA blocks', 'bn' => 'কনট্যাক্ট ফর্ম, সার্ভিস সেকশন ও CTA ব্লক'],
                    ['en' => 'Priority maintenance and content updates', 'bn' => 'প্রায়োরিটি মেইনটেন্যান্স ও কনটেন্ট আপডেট'],
                ],
                'featured' => true,
            ],
            [
                'badge' => ['en' => 'E-commerce', 'bn' => 'ই-কমার্স'],
                'name' => ['en' => 'Store 1999', 'bn' => 'স্টোর ১৯৯৯'],
                'price' => '1999',
                'currency' => ['en' => 'TK', 'bn' => 'টাকা'],
                'period' => ['en' => '/month', 'bn' => '/মাস'],
                'summary' => ['en' => 'A managed e-commerce subscription for businesses ready to sell online with products, orders, and customer-friendly storefronts.', 'bn' => 'প্রোডাক্ট, অর্ডার এবং কাস্টমার-ফ্রেন্ডলি স্টোরফ্রন্টসহ অনলাইনে বিক্রি শুরু করতে প্রস্তুত ব্যবসার জন্য ম্যানেজড ই-কমার্স সাবস্ক্রিপশন।'],
                'features' => [
                    ['en' => 'Online store with product listings', 'bn' => 'প্রোডাক্ট লিস্টিংসহ অনলাইন স্টোর'],
                    ['en' => 'Order flow, inquiry options, and admin management', 'bn' => 'অর্ডার ফ্লো, ইনকোয়ারি অপশন ও অ্যাডমিন ম্যানেজমেন্ট'],
                    ['en' => 'Ongoing support, fixes, and growth updates', 'bn' => 'চলমান সাপোর্ট, ফিক্স এবং গ্রোথ আপডেট'],
                ],
            ],
        ],
    ],
    'services' => [
        [
            'slug' => 'web-development',
            'icon' => 'WD',
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'Web Development', 'bn' => 'ওয়েব ডেভেলপমেন্ট'],
            'excerpt' => ['en' => 'Business websites, portals, SaaS platforms, and custom dashboards.', 'bn' => 'বিজনেস ওয়েবসাইট, পোর্টাল, SaaS প্ল্যাটফর্ম এবং কাস্টম ড্যাশবোর্ড।'],
            'description' => ['en' => 'We build fast, secure, and maintainable web products using Laravel-first architecture with modern frontend patterns where they add value.', 'bn' => 'আমরা Laravel-ভিত্তিক আধুনিক আর্কিটেকচারে দ্রুত, নিরাপদ এবং সহজে রক্ষণাবেক্ষণযোগ্য ওয়েব প্রোডাক্ট তৈরি করি।'],
            'deliverables' => [
                ['en' => 'Marketing and corporate sites', 'bn' => 'মার্কেটিং ও কর্পোরেট সাইট'],
                ['en' => 'Custom admin dashboards', 'bn' => 'কাস্টম অ্যাডমিন ড্যাশবোর্ড'],
                ['en' => 'SaaS application builds', 'bn' => 'SaaS অ্যাপ্লিকেশন ডেভেলপমেন্ট'],
            ],
        ],
        [
            'slug' => 'mobile-apps',
            'icon' => 'MA',
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'Mobile Apps', 'bn' => 'মোবাইল অ্যাপ'],
            'excerpt' => ['en' => 'Cross-platform apps with intuitive journeys and strong API foundations.', 'bn' => 'সহজ ব্যবহারযোগ্য যাত্রাপথ ও শক্তিশালী API ভিত্তিসহ ক্রস-প্ল্যাটফর্ম অ্যাপ।'],
            'description' => ['en' => 'Our team designs and ships mobile experiences that feel polished, lightweight, and aligned with business goals.', 'bn' => 'আমাদের টিম এমন মোবাইল অভিজ্ঞতা ডিজাইন ও তৈরি করে যা পরিপাটি, হালকা এবং ব্যবসায়িক লক্ষ্যসম্মত।'],
            'deliverables' => [
                ['en' => 'Customer-facing mobile products', 'bn' => 'কাস্টমার-ফেসিং মোবাইল প্রোডাক্ট'],
                ['en' => 'Field service apps', 'bn' => 'ফিল্ড সার্ভিস অ্যাপ'],
                ['en' => 'Admin and reporting apps', 'bn' => 'অ্যাডমিন ও রিপোর্টিং অ্যাপ'],
            ],
        ],
        [
            'slug' => 'erp-crm',
            'icon' => 'ER',
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'ERP & CRM Systems', 'bn' => 'ERP ও CRM সিস্টেম'],
            'excerpt' => ['en' => 'Connected operations, sales pipelines, inventory, and reporting in one place.', 'bn' => 'এক জায়গায় অপারেশন, সেলস পাইপলাইন, ইনভেন্টরি ও রিপোর্টিং।'],
            'description' => ['en' => 'We replace manual workflows with business systems that create visibility, control, and better decisions across departments.', 'bn' => 'আমরা ম্যানুয়াল প্রক্রিয়ার বদলে এমন বিজনেস সিস্টেম তৈরি করি যা বিভিন্ন টিমকে দেয় স্বচ্ছতা, নিয়ন্ত্রণ ও ভালো সিদ্ধান্ত।'],
            'deliverables' => [
                ['en' => 'HR and operations modules', 'bn' => 'HR ও অপারেশন মডিউল'],
                ['en' => 'Sales pipeline automation', 'bn' => 'সেলস পাইপলাইন অটোমেশন'],
                ['en' => 'Custom analytics and reports', 'bn' => 'কাস্টম অ্যানালিটিক্স ও রিপোর্ট'],
            ],
        ],
        [
            'slug' => 'ui-ux-design',
            'icon' => 'UX',
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'UI/UX Design', 'bn' => 'UI/UX ডিজাইন'],
            'excerpt' => ['en' => 'Clear information architecture, conversion-focused layouts, and design systems.', 'bn' => 'পরিষ্কার তথ্য স্থাপনা, কনভারশন-কেন্দ্রিক লেআউট এবং ডিজাইন সিস্টেম।'],
            'description' => ['en' => 'Our design process brings user empathy and product clarity together so teams can build with confidence.', 'bn' => 'আমাদের ডিজাইন প্রক্রিয়া ইউজারের প্রয়োজন এবং প্রোডাক্টের স্বচ্ছতাকে একত্রে আনে, যাতে টিম আত্মবিশ্বাসের সাথে তৈরি করতে পারে।'],
            'deliverables' => [
                ['en' => 'Wireframes and interactive flows', 'bn' => 'ওয়্যারফ্রেম ও ইন্টারঅ্যাকটিভ ফ্লো'],
                ['en' => 'Visual direction and UI kits', 'bn' => 'ভিজ্যুয়াল দিকনির্দেশনা ও UI কিট'],
                ['en' => 'Design handoff support', 'bn' => 'ডিজাইন হ্যান্ডঅফ সাপোর্ট'],
            ],
        ],
        [
            'slug' => 'cloud-devops',
            'icon' => 'CD',
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'Cloud & DevOps', 'bn' => 'ক্লাউড ও ডেভঅপস'],
            'excerpt' => ['en' => 'Reliable deployments, optimized hosting, backups, and monitoring.', 'bn' => 'নির্ভরযোগ্য ডিপ্লয়মেন্ট, উন্নত হোস্টিং, ব্যাকআপ ও মনিটরিং।'],
            'description' => ['en' => 'We help teams move from fragile deployments to calm, observable infrastructure that can support growth.', 'bn' => 'আমরা দুর্বল ডিপ্লয়মেন্ট থেকে টিমকে নিয়ে যাই স্থিতিশীল ও পর্যবেক্ষণযোগ্য অবকাঠামোতে, যা স্কেল সামলাতে পারে।'],
            'deliverables' => [
                ['en' => 'CI/CD pipelines', 'bn' => 'CI/CD পাইপলাইন'],
                ['en' => 'Server setup and security hardening', 'bn' => 'সার্ভার সেটআপ ও সিকিউরিটি হার্ডেনিং'],
                ['en' => 'Performance tuning', 'bn' => 'পারফরম্যান্স টিউনিং'],
            ],
        ],
        [
            'slug' => 'it-consulting',
            'icon' => 'IT',
            'image' => '/assets/images/service-card.svg',
            'title' => ['en' => 'IT Consulting', 'bn' => 'আইটি কনসাল্টিং'],
            'excerpt' => ['en' => 'Product direction, technical audits, MVP planning, and modernization advice.', 'bn' => 'প্রোডাক্ট দিকনির্দেশনা, টেকনিক্যাল অডিট, MVP পরিকল্পনা ও আধুনিকীকরণ পরামর্শ।'],
            'description' => ['en' => 'When teams need clarity before they build, we help define the right architecture, roadmap, and delivery sequence.', 'bn' => 'টিম যখন নির্মাণের আগে স্পষ্টতা চায়, আমরা সঠিক আর্কিটেকচার, রোডম্যাপ ও ডেলিভারি ধাপ নির্ধারণে সহায়তা করি।'],
            'deliverables' => [
                ['en' => 'Technical discovery sessions', 'bn' => 'টেকনিক্যাল ডিসকভারি সেশন'],
                ['en' => 'MVP scoping workshops', 'bn' => 'MVP স্কোপিং ওয়ার্কশপ'],
                ['en' => 'Legacy system reviews', 'bn' => 'পুরনো সিস্টেম মূল্যায়ন'],
            ],
        ],
    ],
    'process' => [
        ['step' => '01', 'title' => ['en' => 'Discover', 'bn' => 'ডিসকভার'], 'copy' => ['en' => 'We clarify business goals, constraints, user needs, and success metrics before the build starts.', 'bn' => 'ডেভেলপমেন্ট শুরু হওয়ার আগে আমরা ব্যবসায়িক লক্ষ্য, সীমাবদ্ধতা, ইউজারের প্রয়োজন এবং সাফল্যের মানদণ্ড পরিষ্কার করি।']],
        ['step' => '02', 'title' => ['en' => 'Design', 'bn' => 'ডিজাইন'], 'copy' => ['en' => 'Flows, wireframes, interface direction, and technical planning are aligned into one delivery path.', 'bn' => 'ফ্লো, ওয়্যারফ্রেম, ইন্টারফেস দিকনির্দেশনা এবং টেকনিক্যাল পরিকল্পনাকে একটি ডেলিভারি পথে আনা হয়।']],
        ['step' => '03', 'title' => ['en' => 'Develop', 'bn' => 'ডেভেলপ'], 'copy' => ['en' => 'We build in tight milestones with reviews, demos, and constant communication.', 'bn' => 'আমরা ছোট ছোট মাইলস্টোনে কাজ করি, যেখানে রিভিউ, ডেমো ও নিয়মিত যোগাযোগ থাকে।']],
        ['step' => '04', 'title' => ['en' => 'Support', 'bn' => 'সাপোর্ট'], 'copy' => ['en' => 'Launch, iterate, and keep improving with maintenance, analytics, and roadmap guidance.', 'bn' => 'লঞ্চের পর মেইনটেন্যান্স, অ্যানালিটিক্স এবং রোডম্যাপ সহায়তার মাধ্যমে ক্রমাগত উন্নয়ন চালিয়ে যাই।']],
    ],
    'whyChooseUs' => [
        'eyebrow' => ['en' => 'Why Choose Us', 'bn' => 'কেন আমাদের বেছে নেবেন'],
        'title' => ['en' => 'A Delivery Style Built for Momentum', 'bn' => 'অগ্রগতির জন্য তৈরি ডেলিভারি স্টাইল'],
        'copy' => ['en' => 'We bring strategy, design, engineering, and communication together so projects do not stall between teams.', 'bn' => 'আমরা স্ট্র্যাটেজি, ডিজাইন, ইঞ্জিনিয়ারিং এবং যোগাযোগকে একত্রে আনি, যাতে প্রজেক্ট টিমের মাঝে আটকে না যায়।'],
        'points' => [
            ['title' => ['en' => 'Business-first thinking', 'bn' => 'ব্যবসা-কেন্দ্রিক চিন্তা'], 'description' => ['en' => 'We map features to outcomes, not just specifications.', 'bn' => 'আমরা শুধু স্পেসিফিকেশন নয়, ফলাফলের সাথে ফিচারের সম্পর্ক স্থাপন করি।']],
            ['title' => ['en' => 'Clear communication', 'bn' => 'পরিষ্কার যোগাযোগ'], 'description' => ['en' => 'Weekly updates, shared visibility, and honest scope conversations.', 'bn' => 'সাপ্তাহিক আপডেট, যৌথ দৃশ্যমানতা এবং স্কোপ নিয়ে সৎ আলোচনা।']],
            ['title' => ['en' => 'Scalable architecture', 'bn' => 'স্কেলযোগ্য আর্কিটেকচার'], 'description' => ['en' => 'Builds that stay maintainable as teams and traffic grow.', 'bn' => 'টিম ও ট্রাফিক বাড়লেও রক্ষণাবেক্ষণযোগ্য থাকে এমন বিল্ড।']],
            ['title' => ['en' => 'Long-term partnership', 'bn' => 'দীর্ঘমেয়াদি অংশীদারিত্ব'], 'description' => ['en' => 'Post-launch improvements, optimization, and dependable support.', 'bn' => 'লঞ্চের পর উন্নয়ন, অপ্টিমাইজেশন এবং নির্ভরযোগ্য সাপোর্ট।']],
        ],
        'panel' => [
            'title' => ['en' => 'Trusted for products that need clarity', 'bn' => 'যে প্রোডাক্টে স্বচ্ছতা জরুরি, সেখানে আমাদের উপর আস্থা রাখা হয়'],
            'items' => [
                ['en' => 'Product workshops with founders and stakeholders', 'bn' => 'ফাউন্ডার ও স্টেকহোল্ডারদের সাথে প্রোডাক্ট ওয়ার্কশপ'],
                ['en' => 'Human-centered UX before development', 'bn' => 'ডেভেলপমেন্টের আগে মানব-কেন্দ্রিক UX'],
                ['en' => 'Lean milestones and launch readiness support', 'bn' => 'সংক্ষিপ্ত মাইলস্টোন ও লঞ্চ রেডিনেস সাপোর্ট'],
            ],
        ],
    ],
    'projectIntro' => [
        'eyebrow' => ['en' => 'Our Work', 'bn' => 'আমাদের কাজ'],
        'title' => ['en' => 'Selected Projects', 'bn' => 'নির্বাচিত প্রজেক্ট'],
        'copy' => ['en' => 'A mix of portals, ERP platforms, mobile apps, and customer experiences launched for growing businesses.', 'bn' => 'বর্ধনশীল ব্যবসার জন্য নির্মিত পোর্টাল, ERP প্ল্যাটফর্ম, মোবাইল অ্যাপ ও কাস্টমার অভিজ্ঞতার মিশ্রণ।'],
    ],
    'projectCategories' => [
        ['key' => 'all', 'label' => ['en' => 'All', 'bn' => 'সব']],
        ['key' => 'web', 'label' => ['en' => 'Web', 'bn' => 'ওয়েব']],
        ['key' => 'mobile', 'label' => ['en' => 'Mobile', 'bn' => 'মোবাইল']],
        ['key' => 'erp', 'label' => ['en' => 'ERP', 'bn' => 'ERP']],
        ['key' => 'design', 'label' => ['en' => 'Design', 'bn' => 'ডিজাইন']],
    ],
    'projects' => [
        [
            'slug' => 'shopbd-platform',
            'category' => 'web',
            'gradient' => 'mint',
            'image' => '/assets/images/project-card.svg',
            'title' => ['en' => 'ShopBD Online Store', 'bn' => 'ShopBD অনলাইন স্টোর'],
            'summary' => ['en' => 'A scalable e-commerce platform with campaign tools, seller management, and conversion-focused storefronts.', 'bn' => 'ক্যাম্পেইন টুল, সেলার ম্যানেজমেন্ট এবং কনভারশন-কেন্দ্রিক স্টোরফ্রন্টসহ একটি স্কেলযোগ্য ই-কমার্স প্ল্যাটফর্ম।'],
            'tech' => 'Laravel · Vue · MySQL',
            'client' => 'ShopBD',
            'year' => '2025',
        ],
        [
            'slug' => 'hr-pro-bd',
            'category' => 'erp',
            'gradient' => 'sky',
            'image' => '/assets/images/project-card.svg',
            'title' => ['en' => 'HR Pro Bangladesh', 'bn' => 'HR Pro Bangladesh'],
            'summary' => ['en' => 'Attendance, leave, payroll, and reporting workflows unified into one admin system.', 'bn' => 'অ্যাটেনডেন্স, ছুটি, পেরোল এবং রিপোর্টিংকে একত্রে আনা একটি অ্যাডমিন সিস্টেম।'],
            'tech' => 'Laravel · React · MySQL',
            'client' => 'PeopleOps Group',
            'year' => '2024',
        ],
        [
            'slug' => 'fastdeliver-mobile',
            'category' => 'mobile',
            'gradient' => 'violet',
            'image' => '/assets/images/project-card.svg',
            'title' => ['en' => 'FastDeliver Mobile', 'bn' => 'FastDeliver মোবাইল'],
            'summary' => ['en' => 'A courier app for parcel booking, rider tracking, proof of delivery, and support.', 'bn' => 'পার্সেল বুকিং, রাইডার ট্র্যাকিং, ডেলিভারি প্রুফ এবং সাপোর্টসহ একটি কুরিয়ার অ্যাপ।'],
            'tech' => 'Flutter · Laravel API',
            'client' => 'FastDeliver',
            'year' => '2025',
        ],
        [
            'slug' => 'retailpos-bd',
            'category' => 'erp',
            'gradient' => 'coral',
            'image' => '/assets/images/project-card.svg',
            'title' => ['en' => 'RetailPOS BD', 'bn' => 'RetailPOS BD'],
            'summary' => ['en' => 'A multi-branch POS and inventory platform for retail chains with finance-ready reporting.', 'bn' => 'রিটেইল চেইনের জন্য মাল্টি-ব্রাঞ্চ POS ও ইনভেন্টরি প্ল্যাটফর্ম, যেখানে রয়েছে ফাইন্যান্স-রেডি রিপোর্টিং।'],
            'tech' => 'Laravel · Inertia · MySQL',
            'client' => 'RetailPOS',
            'year' => '2024',
        ],
        [
            'slug' => 'edutrack-bd',
            'category' => 'web',
            'gradient' => 'lime',
            'image' => '/assets/images/project-card.svg',
            'title' => ['en' => 'EduTrack Campus Platform', 'bn' => 'EduTrack ক্যাম্পাস প্ল্যাটফর্ম'],
            'summary' => ['en' => 'Admissions, results, fee tracking, and parent communication for education institutes.', 'bn' => 'শিক্ষাপ্রতিষ্ঠানের জন্য অ্যাডমিশন, রেজাল্ট, ফি ট্র্যাকিং এবং অভিভাবক যোগাযোগ ব্যবস্থা।'],
            'tech' => 'Laravel · Alpine · MySQL',
            'client' => 'EduTrack',
            'year' => '2023',
        ],
        [
            'slug' => 'moneyflow-mobile',
            'category' => 'design',
            'gradient' => 'sun',
            'image' => '/assets/images/project-card.svg',
            'title' => ['en' => 'MoneyFlow Finance App', 'bn' => 'MoneyFlow ফাইন্যান্স অ্যাপ'],
            'summary' => ['en' => 'A fintech product design system and onboarding flow created for faster adoption.', 'bn' => 'দ্রুত ব্যবহার গ্রহণের জন্য তৈরি একটি ফিনটেক ডিজাইন সিস্টেম ও অনবোর্ডিং ফ্লো।'],
            'tech' => 'Figma · UX Research · Prototyping',
            'client' => 'MoneyFlow',
            'year' => '2025',
        ],
    ],
    'testimonials' => [
        [
            'name' => 'Rafiq Karim',
            'role' => ['en' => 'CEO, ShopBD', 'bn' => 'সিইও, ShopBD'],
            'message' => ['en' => 'TechOrbit IT delivered our e-commerce platform with strong communication and thoughtful product suggestions throughout the build.', 'bn' => 'TechOrbit IT আমাদের ই-কমার্স প্ল্যাটফর্ম তৈরি করেছে দারুণ যোগাযোগ এবং পুরো প্রক্রিয়ায় কার্যকর প্রোডাক্ট পরামর্শ দিয়ে।'],
        ],
        [
            'name' => 'Sharmin Akter',
            'role' => ['en' => 'Managing Director, TextilePro BD', 'bn' => 'ম্যানেজিং ডিরেক্টর, TextilePro BD'],
            'message' => ['en' => 'Their ERP work gave us visibility across departments and replaced a lot of manual reporting pain.', 'bn' => 'তাদের ERP কাজ আমাদের বিভিন্ন ডিপার্টমেন্টে পরিষ্কার দৃশ্যমানতা দিয়েছে এবং অনেক ম্যানুয়াল রিপোর্টিংয়ের ঝামেলা দূর করেছে।'],
        ],
        [
            'name' => 'Mahbub Hassan',
            'role' => ['en' => 'CTO, FinTech BD', 'bn' => 'সিটিও, FinTech BD'],
            'message' => ['en' => 'Professional, reliable, and easy to work with. Their team thinks carefully about both code and product experience.', 'bn' => 'প্রফেশনাল, নির্ভরযোগ্য এবং কাজের জন্য খুব সহজ। তাদের টিম কোড এবং প্রোডাক্ট এক্সপেরিয়েন্স দুটো নিয়েই মনোযোগ দিয়ে ভাবে।'],
        ],
    ],
    'technologies' => ['Laravel', 'PHP', 'MySQL', 'Flutter', 'React', 'AWS', 'Docker', 'Tailwind', 'Figma', 'Alpine.js'],
    'blogIntro' => [
        'eyebrow' => ['en' => 'Latest Insights', 'bn' => 'সর্বশেষ ইনসাইট'],
        'title' => ['en' => 'From Our Blog', 'bn' => 'আমাদের ব্লগ থেকে'],
        'copy' => ['en' => 'Practical articles on shipping better digital products, improving internal systems, and making technical decisions with confidence.', 'bn' => 'আরও ভালো ডিজিটাল প্রোডাক্ট তৈরি, অভ্যন্তরীণ সিস্টেম উন্নত করা এবং আত্মবিশ্বাসের সাথে টেকনিক্যাল সিদ্ধান্ত নেওয়া নিয়ে বাস্তবধর্মী লেখা।'],
    ],
    'blogCategories' => [
        ['name' => ['en' => 'Product Strategy', 'bn' => 'প্রোডাক্ট স্ট্র্যাটেজি']],
        ['name' => ['en' => 'Laravel', 'bn' => 'Laravel']],
        ['name' => ['en' => 'UX Design', 'bn' => 'UX ডিজাইন']],
        ['name' => ['en' => 'Digital Transformation', 'bn' => 'ডিজিটাল ট্রান্সফরমেশন']],
    ],
    'posts' => [
        [
            'category' => ['en' => 'Product Strategy', 'bn' => 'প্রোডাক্ট স্ট্র্যাটেজি'],
            'date' => '04 Apr 2026',
            'title' => ['en' => 'How to Scope an MVP Without Cutting the Wrong Features', 'bn' => 'ভুল ফিচার বাদ না দিয়ে কীভাবে একটি MVP এর স্কোপ ঠিক করবেন'],
            'excerpt' => ['en' => 'A practical framework for balancing urgency, technical risk, and user value when your first release needs to be lean.', 'bn' => 'প্রথম রিলিজকে সংক্ষিপ্ত রাখার সময় জরুরি প্রয়োজন, টেকনিক্যাল ঝুঁকি এবং ইউজার ভ্যালুর মধ্যে ভারসাম্য আনার একটি বাস্তবধর্মী ফ্রেমওয়ার্ক।'],
            'read_time' => ['en' => '6 min read', 'bn' => '৬ মিনিট পড়ুন'],
        ],
        [
            'category' => ['en' => 'Laravel', 'bn' => 'Laravel'],
            'date' => '19 Mar 2026',
            'title' => ['en' => 'Patterns We Use to Keep Laravel Projects Maintainable', 'bn' => 'Laravel প্রজেক্টগুলোকে রক্ষণাবেক্ষণযোগ্য রাখতে আমরা যেসব প্যাটার্ন ব্যবহার করি'],
            'excerpt' => ['en' => 'Structure, communication, and architectural habits that help teams move faster long after launch day.', 'bn' => 'লঞ্চের অনেক পরেও টিমকে দ্রুত কাজ করতে সহায়তা করে এমন স্ট্রাকচার, যোগাযোগ এবং আর্কিটেকচারাল অভ্যাস।'],
            'read_time' => ['en' => '5 min read', 'bn' => '৫ মিনিট পড়ুন'],
        ],
        [
            'category' => ['en' => 'UX Design', 'bn' => 'UX ডিজাইন'],
            'date' => '02 Mar 2026',
            'title' => ['en' => 'Why Internal Tools Need Good UX Just as Much as Customer Apps', 'bn' => 'কেন অভ্যন্তরীণ টুলগুলোরও কাস্টমার অ্যাপের মতো ভালো UX দরকার'],
            'excerpt' => ['en' => 'Small design decisions can remove friction from daily operations and save teams hours every week.', 'bn' => 'ছোট ছোট ডিজাইন সিদ্ধান্ত প্রতিদিনের কাজে বাধা কমাতে পারে এবং প্রতি সপ্তাহে টিমের অনেক সময় বাঁচাতে পারে।'],
            'read_time' => ['en' => '4 min read', 'bn' => '৪ মিনিট পড়ুন'],
        ],
    ],
    'about' => [
        'eyebrow' => ['en' => 'About TechOrbit', 'bn' => 'TechOrbit সম্পর্কে'],
        'title' => ['en' => 'We Build Calm, Useful Software for Growing Teams', 'bn' => 'আমরা বর্ধনশীল টিমের জন্য স্থির ও কার্যকর সফটওয়্যার তৈরি করি'],
        'story' => ['en' => 'TechOrbit IT started with a simple belief: software should reduce confusion, not create more of it. We partner with businesses that need dependable systems, thoughtful interfaces, and a team that communicates clearly from kickoff to launch.', 'bn' => 'TechOrbit IT শুরু হয়েছিল একটি সাধারণ বিশ্বাস থেকে: সফটওয়্যার বিভ্রান্তি কমাবে, বাড়াবে না। আমরা এমন ব্যবসার সাথে কাজ করি, যাদের দরকার নির্ভরযোগ্য সিস্টেম, চিন্তাশীল ইন্টারফেস এবং শুরু থেকে লঞ্চ পর্যন্ত পরিষ্কার যোগাযোগ।'],
        'mission' => ['en' => 'To design and deliver digital systems that help ambitious businesses operate with more clarity and confidence.', 'bn' => 'উদ্যোগী ব্যবসাগুলোকে আরও স্বচ্ছতা ও আত্মবিশ্বাসের সাথে কাজ করতে সহায়তা করে এমন ডিজিটাল সিস্টেম ডিজাইন ও ডেলিভারি করা।'],
        'vision' => ['en' => 'To be a trusted product and engineering partner for organizations across Bangladesh and beyond.', 'bn' => 'বাংলাদেশসহ বিভিন্ন প্রতিষ্ঠানের জন্য একটি বিশ্বস্ত প্রোডাক্ট ও ইঞ্জিনিয়ারিং পার্টনার হওয়া।'],
    ],
    'values' => [
        ['title' => ['en' => 'Clarity', 'bn' => 'স্বচ্ছতা'], 'copy' => ['en' => 'We make complex work understandable for clients, teams, and stakeholders.', 'bn' => 'আমরা জটিল কাজকে ক্লায়েন্ট, টিম এবং স্টেকহোল্ডারদের জন্য বোধগম্য করি।']],
        ['title' => ['en' => 'Momentum', 'bn' => 'অগ্রগতি'], 'copy' => ['en' => 'Small, visible progress matters more than big promises.', 'bn' => 'বড় প্রতিশ্রুতির চেয়ে ছোট কিন্তু দৃশ্যমান অগ্রগতি বেশি গুরুত্বপূর্ণ।']],
        ['title' => ['en' => 'Ownership', 'bn' => 'দায়িত্ববোধ'], 'copy' => ['en' => 'We care about the outcome, not just the task list.', 'bn' => 'আমরা শুধু টাস্ক লিস্ট নয়, শেষ ফলাফল নিয়েও দায়িত্ব নিই।']],
        ['title' => ['en' => 'Partnership', 'bn' => 'অংশীদারিত্ব'], 'copy' => ['en' => 'We work with clients as collaborators, not ticket queues.', 'bn' => 'আমরা ক্লায়েন্টদের সাথে টিকিট কিউ নয়, অংশীদার হিসেবে কাজ করি।']],
    ],
    'team' => [
        ['initials' => 'AI', 'name' => 'Amina Islam', 'image' => '/assets/images/team-card.svg', 'role' => ['en' => 'Founder & Product Lead', 'bn' => 'ফাউন্ডার ও প্রোডাক্ট লিড']],
        ['initials' => 'RH', 'name' => 'Rakib Hossain', 'image' => '/assets/images/team-card.svg', 'role' => ['en' => 'Engineering Manager', 'bn' => 'ইঞ্জিনিয়ারিং ম্যানেজার']],
        ['initials' => 'SN', 'name' => 'Sumaiya Nahar', 'image' => '/assets/images/team-card.svg', 'role' => ['en' => 'UX Designer', 'bn' => 'UX ডিজাইনার']],
        ['initials' => 'MF', 'name' => 'Mehedi Faisal', 'image' => '/assets/images/team-card.svg', 'role' => ['en' => 'Mobile Lead', 'bn' => 'মোবাইল লিড']],
    ],
    'milestones' => [
        ['year' => '2019', 'title' => ['en' => 'TechOrbit launched', 'bn' => 'TechOrbit এর যাত্রা শুরু'], 'copy' => ['en' => 'Started as a small software delivery team serving local businesses.', 'bn' => 'স্থানীয় ব্যবসাগুলোর জন্য কাজ করা একটি ছোট সফটওয়্যার ডেলিভারি টিম হিসেবে শুরু।']],
        ['year' => '2021', 'title' => ['en' => 'Expanded into ERP and CRM delivery', 'bn' => 'ERP ও CRM ডেলিভারিতে প্রসার'], 'copy' => ['en' => 'Built custom business systems for operations-heavy organizations.', 'bn' => 'অপারেশন-নির্ভর প্রতিষ্ঠানের জন্য কাস্টম বিজনেস সিস্টেম তৈরি।']],
        ['year' => '2023', 'title' => ['en' => 'Launched mobile and design practice', 'bn' => 'মোবাইল ও ডিজাইন ইউনিট চালু'], 'copy' => ['en' => 'Added mobile product work and stronger design systems to the offer.', 'bn' => 'সেবার পরিধিতে মোবাইল প্রোডাক্ট এবং আরও শক্তিশালী ডিজাইন সিস্টেম যুক্ত হয়।']],
        ['year' => '2026', 'title' => ['en' => 'Scaling with long-term clients', 'bn' => 'দীর্ঘমেয়াদি ক্লায়েন্টদের সাথে স্কেলিং'], 'copy' => ['en' => 'Supporting repeat partners across product launches and modernization projects.', 'bn' => 'প্রোডাক্ট লঞ্চ ও আধুনিকীকরণ প্রজেক্টে পুনরায় আসা ক্লায়েন্টদের সহায়তা।']],
    ],
    'contact' => [
        'eyebrow' => ['en' => 'Contact Us', 'bn' => 'যোগাযোগ করুন'],
        'title' => ['en' => 'Let’s Talk About Your Next Build', 'bn' => 'আপনার পরবর্তী প্রজেক্ট নিয়ে কথা বলি'],
        'copy' => ['en' => 'Share your goals, timeline, or rough idea. We will help shape the right next step.', 'bn' => 'আপনার লক্ষ্য, টাইমলাইন বা প্রাথমিক আইডিয়া জানান। আমরা সঠিক পরবর্তী ধাপ নির্ধারণে সাহায্য করব।'],
        'info_title' => ['en' => 'Get in Touch', 'bn' => 'যোগাযোগের তথ্য'],
        'form_title' => ['en' => 'Send a Message', 'bn' => 'বার্তা পাঠান'],
        'map_title' => ['en' => 'Dhaka, Bangladesh', 'bn' => 'ঢাকা, বাংলাদেশ'],
        'office_hours' => ['en' => 'Sat - Thu, 09:00 AM - 06:00 PM', 'bn' => 'শনি - বৃহস্পতি, সকাল ৯টা - সন্ধ্যা ৬টা'],  
        'services' => [
            ['value' => 'Web Development', 'label' => ['en' => 'Web Development', 'bn' => 'ওয়েব ডেভেলপমেন্ট']],
            ['value' => 'Mobile App', 'label' => ['en' => 'Mobile App', 'bn' => 'মোবাইল অ্যাপ']],
            ['value' => 'ERP / CRM', 'label' => ['en' => 'ERP / CRM', 'bn' => 'ERP / CRM']],
            ['value' => 'UI/UX Design', 'label' => ['en' => 'UI/UX Design', 'bn' => 'UI/UX ডিজাইন']],
            ['value' => 'Consulting', 'label' => ['en' => 'Consulting', 'bn' => 'কনসাল্টিং']],
        ],
        'budgets' => [
            ['value' => '$500 - $2,000', 'label' => ['en' => '$500 - $2,000', 'bn' => '$500 - $2,000']],
            ['value' => '$2,000 - $5,000', 'label' => ['en' => '$2,000 - $5,000', 'bn' => '$2,000 - $5,000']],
            ['value' => '$5,000 - $15,000', 'label' => ['en' => '$5,000 - $15,000', 'bn' => '$5,000 - $15,000']],
            ['value' => '$15,000+', 'label' => ['en' => '$15,000+', 'bn' => '$15,000+']],
        ],
    ],
    'faq' => [
        ['question' => ['en' => 'How quickly can you start?', 'bn' => 'আপনারা কত দ্রুত কাজ শুরু করতে পারেন?'], 'answer' => ['en' => 'Most projects can begin within one to two weeks after scope alignment.', 'bn' => 'স্কোপ চূড়ান্ত হওয়ার পর অধিকাংশ প্রজেক্ট এক থেকে দুই সপ্তাহের মধ্যে শুরু করা যায়।']],
        ['question' => ['en' => 'Do you work with existing systems?', 'bn' => 'আপনারা কি বিদ্যমান সিস্টেমের সাথে কাজ করেন?'], 'answer' => ['en' => 'Yes. We often improve, extend, or modernize systems that are already in use.', 'bn' => 'হ্যাঁ। আমরা প্রায়ই ব্যবহৃত সিস্টেম উন্নত, সম্প্রসারণ বা আধুনিকায়ন করি।']],
        ['question' => ['en' => 'Can you provide ongoing support?', 'bn' => 'আপনারা কি চলমান সাপোর্ট দেন?'], 'answer' => ['en' => 'Yes, we offer post-launch support, optimization, and maintenance plans.', 'bn' => 'হ্যাঁ, আমরা লঞ্চ-পরবর্তী সাপোর্ট, অপ্টিমাইজেশন এবং মেইনটেন্যান্স প্ল্যান দিই।']],
    ],
    'admin' => [
        'menu' => [
            ['section' => 'Main', 'items' => [['label' => 'Dashboard', 'active' => true, 'badge' => null]]],
            ['section' => 'Content', 'items' => [['label' => 'Hero Slides', 'active' => false, 'badge' => null], ['label' => 'Services', 'active' => false, 'badge' => null], ['label' => 'Portfolio', 'active' => false, 'badge' => null], ['label' => 'Team', 'active' => false, 'badge' => null], ['label' => 'Blog', 'active' => false, 'badge' => null]]],
            ['section' => 'Manage', 'items' => [['label' => 'Inquiries', 'active' => false, 'badge' => '7'], ['label' => 'Testimonials', 'active' => false, 'badge' => null], ['label' => 'Settings', 'active' => false, 'badge' => null]]],
        ],
        'stats' => [
            ['label' => 'Total Projects', 'value' => '54', 'change' => '+3 this month', 'tone' => 'teal'],
            ['label' => 'New Inquiries', 'value' => '7', 'change' => '+2 today', 'tone' => 'gold'],
            ['label' => 'Blog Posts', 'value' => '23', 'change' => 'Published', 'tone' => 'green'],
            ['label' => 'Team Members', 'value' => '12', 'change' => 'Active', 'tone' => 'blue'],
        ],
        'inquiries' => [
            ['initials' => 'RK', 'name' => 'Rafiq Karim', 'service' => 'Web Development', 'date' => 'Today, 2:30 PM', 'status' => 'New', 'tone' => 'new'],
            ['initials' => 'SA', 'name' => 'Sadia Ahmed', 'service' => 'Mobile App', 'date' => 'Today, 10:15 AM', 'status' => 'Read', 'tone' => 'read'],
            ['initials' => 'MH', 'name' => 'Mahbub Hasan', 'service' => 'ERP System', 'date' => 'Yesterday', 'status' => 'Replied', 'tone' => 'replied'],
            ['initials' => 'FJ', 'name' => 'Farhan Jahan', 'service' => 'UI/UX Design', 'date' => 'Yesterday', 'status' => 'New', 'tone' => 'new'],
            ['initials' => 'NB', 'name' => 'Nadia Begum', 'service' => 'IT Consulting', 'date' => '2 days ago', 'status' => 'Replied', 'tone' => 'replied'],
        ],
        'chart' => [
            ['month' => 'Nov', 'height' => 40, 'tone' => 'soft'],
            ['month' => 'Dec', 'height' => 56, 'tone' => 'soft'],
            ['month' => 'Jan', 'height' => 48, 'tone' => 'soft'],
            ['month' => 'Feb', 'height' => 68, 'tone' => 'soft'],
            ['month' => 'Mar', 'height' => 60, 'tone' => 'soft'],
            ['month' => 'Apr', 'height' => 84, 'tone' => 'strong'],
        ],
        'actions' => [
            ['title' => 'Add New Project', 'abbr' => 'PR', 'tone' => 'teal'],
            ['title' => 'Write Blog Post', 'abbr' => 'BL', 'tone' => 'gold'],
            ['title' => 'Add Team Member', 'abbr' => 'TM', 'tone' => 'green'],
            ['title' => 'Update Services', 'abbr' => 'SV', 'tone' => 'blue'],
            ['title' => 'Manage Hero Slides', 'abbr' => 'HS', 'tone' => 'coral'],
            ['title' => 'SEO Settings', 'abbr' => 'SEO', 'tone' => 'purple'],
        ],
    ],
];

